/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-22 06:40:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class check_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\n");
      out.write("<title>나를지켜줘</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

	//==========자기점검코너==========
		//세션이 유지되는지 검사
		String userID = null;
		if(session.getAttribute("userID") != null) {
			userID = (String) session.getAttribute("userID");
		}
	
      out.write("\n");
      out.write("\t<nav class=\"navbar navbar-default\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\n");
      out.write("\t\t\t\taria-expanded=\"false\">\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"main.jsp\">나를지켜줘</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"main.jsp\">성범죄 상담소</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"population.jsp\">성범죄 인구수</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"bbs.jsp\">온라인 상담</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"question.jsp\">자주묻는질문</a></li>\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"check.jsp\">자기점검코너</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"law.jsp\">법률개정안내</a></li>\n");
      out.write("\t\t\t\t");

				if("admin".equals(userID)) {
				
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"admin.jsp\">관리자페이지</a></li>\t\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t");

				//세션이 없다면 -> 로그인, 회원가입 가능
				if(userID == null) {
			
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t");

				//세션이 있다면 -> 로그아웃, 회원탈퇴 가능
				} else {
			
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">회원관리<span class=\"caret\"></span></a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a onclick=\"return confirm('정말로 탈퇴하시겠습니까?')\" href=\"removeAction.jsp\">회원탈퇴</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\t\t\t\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"jumbotron\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<h1>자기점검코너</h1>\t\t\t\t\n");
      out.write("\t\t\t\t<br /><p>나의 성희롱,성폭력 인지력 테스트\n");
      out.write("\t\t\t\t<br />(출처 : 한국대학성평등상담소협의회, 2013 추계워크샵 자료집)</p>\n");
      out.write("\t\t\t\t<p id=\"checkstring\">1. 성추행 사건이 발생했을 경우, 노출이 심한 옷을 입은 상대방도 책임이 있다고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select1' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">2. 나의 제안에 상대방이 침묵했다는 것은 나의 제의를 받아들인다는 의미라고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select2' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">3. 나는 스킨십이나 성적인 접촉을 하기 전에 상대방에게 동의를 구하는 것이 찌질하다고 생각한다.<br /></p>\n");
      out.write("\t\t\t\t\t<select id='select3' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">4. 나의 성적 제의에 상대방이 ‘싫다’라고 말할 때, 속으론 좋으면서 튕귄다고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select4' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">5. 혼자 있는 내 자취방에 상대방이 흔쾌히 들어왔다는 것은 성적 관계를 허락한 것이므로 성적 행동에 합의가 된 것이라고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select5' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">6. 친밀한 사이에서는 동의를 구하지 않아도 가벼운 스킨십은 가능하다고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select6' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">7. 둘이서 함께 찍은 가벼운 스킨십 사진은 상대방의 동의없이도 내 블로그에 올려도 된다고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select7' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">8. 나는 동영상의 야한장면을 실천에 옮기고 싶다는 환상을 갖고 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select8' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">9. 상대방의 외모나 몸매에 대해 친구들과 말하는 것은 나의 자유다.</p>\n");
      out.write("\t\t\t\t\t<select id='select9' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">10. 성적 농담으로 화기애애해지면 우리 중에 몇몇 불편한 사람이 있어도 팀워크면에서는 괜찮다고 생각한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select10' onChange=\"setValues1();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">아니다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p><button class=\"btn btn-primary btn-pull\" onclick=\"getValues1();\">결과확인</button></p>\n");
      out.write("\t\t\t\t<script>\n");
      out.write("\t\t\t\t//위 질문들을 처리하기 위한 과정\n");
      out.write("\t\t\t\t\tvar xx1 = 0;\n");
      out.write("\t\t\t\t//설문조사 선택사항 데이터 수집 -> 합계\n");
      out.write("\t\t\t\t    function setValues1(){\n");
      out.write("\t\t\t\t    \tvar x1 = document.getElementById(\"select1\").value;\n");
      out.write("\t\t\t\t    \tvar x2 = document.getElementById(\"select2\").value;\n");
      out.write("\t\t\t\t    \tvar x3 = document.getElementById(\"select3\").value;\n");
      out.write("\t\t\t\t    \tvar x4 = document.getElementById(\"select4\").value;\n");
      out.write("\t\t\t\t    \tvar x5 = document.getElementById(\"select5\").value;\n");
      out.write("\t\t\t\t    \tvar x6 = document.getElementById(\"select6\").value;\n");
      out.write("\t\t\t\t    \tvar x7 = document.getElementById(\"select7\").value;\n");
      out.write("\t\t\t\t    \tvar x8 = document.getElementById(\"select8\").value;\n");
      out.write("\t\t\t\t    \tvar x9 = document.getElementById(\"select9\").value;\n");
      out.write("\t\t\t\t    \tvar x10 = document.getElementById(\"select10\").value;\n");
      out.write("\t\t\t\t    \txx1 = Number(x1)+Number(x2)+Number(x3)+Number(x4)+Number(x5)+Number(x6)+Number(x7)+Number(x8)+Number(x9)+Number(x10);\t\t\t\t    \t\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t//설문조사 결과 출력\n");
      out.write("\t\t\t\t    function getValues1(){\n");
      out.write("\t\t\t\t    \tif (xx1<1) {\n");
      out.write("\t\t\t\t    \t\talert(\"당신은 충분한 성교육을 받고 있습니다.\");\n");
      out.write("\t\t\t\t    \t} else if (xx1>=1 && xx1<4){\n");
      out.write("\t\t\t\t    \t\talert(\"2% 아쉽습니다. 조금 더 노력하세요.\");\t\t\t\t    \t\t\n");
      out.write("\t\t\t\t    \t} else if (xx1>=4 && xx1<7){\n");
      out.write("\t\t\t\t    \t\talert(\"의식개선이 필요합니다.\");\t\t\t\t    \t\t\n");
      out.write("\t\t\t\t    \t} else if (xx1>=7){\n");
      out.write("\t\t\t\t    \t\talert(\"주기적인 성교육이 필요합니다.\");\t\t\t\t    \t\t\n");
      out.write("\t\t\t\t    \t}\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<br /><br /><br /><p>성적 의사결정능력\n");
      out.write("\t\t\t\t<br />(출처: 한국여성민우회 가족과 성 상담소)</p>\n");
      out.write("\t\t\t\t<p id=\"checkstring\">1. 좋아하다가 싫어지는 감정이 생길 수 있다는 걸 인정하고 받아들일 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select11' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">2. 나는 성적 욕망이나 지식에 대해 상대에게 이야기할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select12' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">3. 상대에게 화났을 때, 고마울 때 등의 감정을 표현할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select13' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">4. 상대가 어떻게 반응할지 걱정되더라도 감정을 감추거나 왜곡하지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select14' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">5. 상대의 일방적인 요구에 대해 ‘부당함’을 이야기 할 수 있다.</p>\t\n");
      out.write("\t\t\t\t\t<select id='select15' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">6. 나는 원하지만 상대가 싫다고 하면 여러 번 반복해서 강요하지 않고 상대의 의사를 존중한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select16' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">7. 나는 여전히 좋아하는데, 상대는 좋아하지 않는다며 헤어지려할 때, 억지로 붙잡지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select17' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">8. 나는 나의 성적인 욕망에 대해 그대로 인정한다.</p>\n");
      out.write("\t\t\t\t\t<select id='select18' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">9. 나는 나에게 맞는 피임법에 대해 알고 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select19' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">10. 성적 욕망이 생기면 함께 나눌 상대가 없어도 나름대로 해소할 수 있는 방법을 알고 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select20' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">11. 성관계 의사 없이도 상대와 여행을 함께 할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select21' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">12. 내 감정과 느낌이 소중한 만큼 상대의 상태를 충분히 고려하고 배려할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select22' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">13. 상대의 감정을 통제하기 위해 내 감정을 과장하거나 왜곡되게 표현하지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select23' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">14. 합의된 신체적인 접촉(예, 키스)을 하는 중에 내 맘대로 다른 행동을 저지르는 행위는 하지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select24' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">15. 상대의 신체적 접촉에 대한 제안을 내가 원하지 않을 경우엔 거절할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select25' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">16. 연애하고 싶은 사람이 생길 때, 상대에게 제안해 볼 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select26' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">17. 나는 사람을 사귈 때 ‘이 사람은 내꺼다’라는 생각을 우선하지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select27' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\n");
      out.write("\t\t\t\t<p id=\"checkstring\">18. 내가 고백했을 때, 상대가 나에 대해 관심이 없다고 말해도 자존심이 상하긴 하지만 받아들일 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select28' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">19. 상대가 취해서 정신이 없을 때를 기회로 내가 평소에 원했던 접촉을 시도하는 일은 하지 않는다.</p>\n");
      out.write("\t\t\t\t\t<select id='select29' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"checkstring\">20. 성적으로 끌리는 대상이 있으면, 그 사람이 생각하고 판단할 수 있는 상황에서 성관계를 제안할 수 있다.</p>\n");
      out.write("\t\t\t\t\t<select id='select30' onChange=\"setValues2();\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">점수</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">전혀 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">다소 그렇지 않다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">중간</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">다소 그렇다</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">매우 그렇다</option>\n");
      out.write("\t\t\t\t\t</select><br /><br />\t\t\n");
      out.write("\t\t\t\t<p><button class=\"btn btn-primary btn-pull\" onclick=\"getValues2();\">결과확인</button></p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<script>\n");
      out.write("\t\t\t\t//위 질문들을 처리하기 위한 과정\n");
      out.write("\t\t\t\t\tvar xx2 = 0;\n");
      out.write("\t\t\t\t//설문조사 선택사항 데이터 수집 -> 합계\n");
      out.write("\t\t\t\t    function setValues2(){\n");
      out.write("\t\t\t\t    \tvar x1 = document.getElementById(\"select11\").value;\n");
      out.write("\t\t\t\t    \tvar x2 = document.getElementById(\"select12\").value;\n");
      out.write("\t\t\t\t    \tvar x3 = document.getElementById(\"select13\").value;\n");
      out.write("\t\t\t\t    \tvar x4 = document.getElementById(\"select14\").value;\n");
      out.write("\t\t\t\t    \tvar x5 = document.getElementById(\"select15\").value;\n");
      out.write("\t\t\t\t    \tvar x6 = document.getElementById(\"select16\").value;\n");
      out.write("\t\t\t\t    \tvar x7 = document.getElementById(\"select17\").value;\n");
      out.write("\t\t\t\t    \tvar x8 = document.getElementById(\"select18\").value;\n");
      out.write("\t\t\t\t    \tvar x9 = document.getElementById(\"select19\").value;\n");
      out.write("\t\t\t\t    \tvar x10 = document.getElementById(\"select20\").value;\n");
      out.write("\t\t\t\t    \tvar x11 = document.getElementById(\"select21\").value;\n");
      out.write("\t\t\t\t    \tvar x12 = document.getElementById(\"select22\").value;\n");
      out.write("\t\t\t\t    \tvar x13 = document.getElementById(\"select23\").value;\n");
      out.write("\t\t\t\t    \tvar x14 = document.getElementById(\"select24\").value;\n");
      out.write("\t\t\t\t    \tvar x15 = document.getElementById(\"select25\").value;\n");
      out.write("\t\t\t\t    \tvar x16 = document.getElementById(\"select26\").value;\n");
      out.write("\t\t\t\t    \tvar x17 = document.getElementById(\"select27\").value;\n");
      out.write("\t\t\t\t    \tvar x18 = document.getElementById(\"select28\").value;\n");
      out.write("\t\t\t\t    \tvar x19 = document.getElementById(\"select29\").value;\n");
      out.write("\t\t\t\t    \tvar x20 = document.getElementById(\"select30\").value;\n");
      out.write("\t\t\t\t    \txx2 = Number(x1)+Number(x2)+Number(x3)+Number(x4)+Number(x5)+Number(x6)+Number(x7)+Number(x8)+Number(x9)+Number(x10)+Number(x11)+Number(x12)+Number(x13)+Number(x14)+Number(x15)+Number(x16)+Number(x17)+Number(x18)+Number(x19)+Number(x20);\t\t\t\t    \t\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t//설문조사 결과 출력\n");
      out.write("\t\t\t\t    function getValues2(){\n");
      out.write("\t\t\t\t    \tif (xx2<=80) {\n");
      out.write("\t\t\t\t    \t\talert(\"자신의 감정과 욕구에 대해 잘 알지 못하고 주장하지 못하고 있습니다. 지금과 같은 상태라면 성적인 가해자나 피해자가 될 가능성이 있어요. 노력하세요.\");\n");
      out.write("\t\t\t\t    \t} else if (xx2>80 && xx2<=92) {\n");
      out.write("\t\t\t\t    \t\talert(\"노력하지만, 상황에 따라 변화가 있네요. 자신의 감정과 욕구를 잘 파악하고 상대를 배려하는 감수성이 더 필요합니다.\");\t\n");
      out.write("\t\t\t\t    \t} else if (xx2>92) {\n");
      out.write("\t\t\t\t    \t\talert(\"자신의 감정이나 욕구에 대해 잘 알고 있으며, 상대의 감정과 욕구를 이해하려고 노력하는군요.\");\n");
      out.write("\t\t\t\t    \t}\t\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
